server:
  port: 50000
spring:
  profiles:
    active: @profiles.active@  # 当前激活配置，默认dev
telegram:
  bot:
    token: 8280891588:AAGgWeooOqlvys-fSj_UU8DBBtwzU1ZaZHM
    username: "moyu_omm_bot"

# 8037300297:AAF1YCfluw9BG4LGXXSEM29a1aXw1Gr0o-0


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mi.manchi.telegram.entity
